### ISSUE TITLE
"face" is not defined

### ISSUE THREAD

**Issue by ghost** [DaFluffyPotato/face-tracker-pyjs#1]
Hi, there. I'm Danix, a developer. I viewed the code of this repo, but if i look good there is an error in poly_3d.py: "face" is not defined but it is called, so that make the script crash.

**Comment by ghost** [comment]
This issue is stale. Time to close it.

**Comment by DaFluffyPotato** [comment]
If you read the readme, it says this repo is a collection of code with some parts gutted out. It's not meant to be immediately functional.

**Comment by ghost** [comment]
> If you read the readme, it says this repo is a collection of code with some parts gutted out. It's not meant to be immediately functional.

Oh, ok

**Comment by Zanark** [comment]
Hi @DaFluffyPotato, just a follow up on this. I'm working on something similar to this and used your repository as an inspiration to work on it. If its okay can you share what exactly is that face variable used for. 

If you have included it in your video then please do let me know and I will get my answer from there.

Huge fan! Love your games!
